# Generated by Django 3.2 on 2021-07-26 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 5, 2, 58, 463964, tzinfo=utc)),
        ),
    ]
