# Generated by Django 3.2 on 2021-07-26 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 8, 49, 22, 77052, tzinfo=utc)),
        ),
    ]
