# Generated by Django 3.2 on 2021-07-26 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 13, 16, 4, 221412, tzinfo=utc)),
        ),
    ]
