# Generated by Django 3.2 on 2021-07-26 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210726_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 13, 17, 59, 142453, tzinfo=utc)),
        ),
    ]
