# Generated by Django 3.2 on 2021-07-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_alter_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandalart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='BigGoal',
            fields=[
                ('manda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mandalart.mandalart')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MidGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('big', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biggoal', to='mandalart.biggoal')),
            ],
        ),
    ]
