# Generated by Django 3.2 on 2021-08-11 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0011_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mandalart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='MidGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BigGoal',
            fields=[
                ('manda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mandalart.mandalart')),
                ('content', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spelist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spelist', to='mandalart.block')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificgoal', to='mandalart.midgoal')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificgoal', to='mandalart.specificgoal')),
                ('spelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='mandalart.spelist')),
            ],
        ),
        migrations.AddField(
            model_name='midgoal',
            name='big',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midgoal', to='mandalart.biggoal'),
        ),
    ]
