# Generated by Django 3.2 on 2021-07-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midgoal', to='mandalart.midgoal')),
            ],
        ),
    ]
