# Generated by Django 3.2 on 2021-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0002_specificgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificgoal',
            name='content',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
