# Generated by Django 3.2 on 2021-07-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0003_specificgoal_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='biggoal',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='midgoal',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificgoal',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
