# Generated by Django 3.2 on 2021-08-12 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandalart', '0003_alter_block_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('user', 'date')},
        ),
    ]
