# Generated by Django 3.2 on 2021-08-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandalart', '0004_auto_20210726_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midgoal',
            name='big',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midgoal', to='mandalart.biggoal'),
        ),
        migrations.AlterField(
            model_name='specificgoal',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificgoal', to='mandalart.midgoal'),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
