# Generated by Django 3.2 on 2021-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0005_auto_20210805_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
