# Generated by Django 3.2 on 2021-08-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0006_block_spelist_spelist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
