# Generated by Django 3.2 on 2021-08-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0007_alter_block_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spelist_item',
            new_name='Item',
        ),
    ]
