# Generated by Django 3.2 on 2021-08-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0008_rename_spelist_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spegoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificgoal', to='mandalart.specificgoal'),
        ),
    ]
