# Generated by Django 3.2 on 2021-08-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0009_alter_item_spegoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='spelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalart.spelist'),
        ),
    ]
