# Generated by Django 3.2 on 2021-08-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0011_alter_item_spelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelist',
            name='block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spelist', to='mandalart.block'),
        ),
    ]
