# Generated by Django 3.2 on 2021-08-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalart', '0012_alter_spelist_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='spegoal',
            new_name='specificgoal',
        ),
    ]
